steps:
  # Instala dependencias desde archivo
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Ejecuta test unitarios
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"] 

  # Compila la imagen y la crea en el repositorio
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'southamerica-west1-docker.pkg.dev/${PROJECT_ID}/py-repo/fastapi:${SHORT_SHA}', '.']

  # Sube imagen compilada a Artifact Repository
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'southamerica-west1-docker.pkg.dev/${PROJECT_ID}/py-repo/fastapi:${SHORT_SHA}']

  # Implementa la función en Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'fastapi-${SHORT_SHA}', 
           '--image=southamerica-west1-docker.pkg.dev/${PROJECT_ID}/py-repo/fastapi:${SHORT_SHA}', 
           '--region', 'southamerica-west1', '--platform', 'managed', 
           '--port', '80',
           '--allow-unauthenticated']

# Guarda archivo de log de pruebas en Cloud Storage
artifacts:
  objects:
    location: gs://liljoint-my-files/
    paths:
      - ${SHORT_SHA}_test_log.xml
# Almacena imagen en Google Artifact Registry 
images:
  - southamerica-west1-docker.pkg.dev/${PROJECT_ID}/py-repo/fastapi:${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
